addons:
  postgresql: '9.3'
  apt:
    sources:
      - ppa:fkrull/deadsnakes
    packages:
      - python3.4

services:
  - redis-server
  - postgresql

script:
  - bash -n script/*
  - bash script/cibuild
