postgres:
  image: postgres

redis:
  image: redis

web:
  build: .
  environment:
    REDIS_URI: redis://redis
  links:
    - postgres
    - redis

nginx:
  build: tools/nginx
  links:
    - web
  ports:
    - '80:80'

ircbot:
  build: tools/ircbot
  environment:
    REDIS_URI: redis://redis
  links:
    - redis
