#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

script/update

source venv/bin/activate

export ENV=development

export DATABASE_URL=postgres://localhost/willtherebespace
export REDIS_URL=redis://localhost/willtherebespace

progress "Starting app…"

foreman start
