#!/bin/sh

set -e

cd "$(dirname "$0")/.."

script/update

brew services restart postgres
brew services restart redis

source venv/bin/activate

export ENV=development

export DATABASE_URL=postgres://localhost/willtherebespace
export REDIS_URL=redis://localhost/willtherebespace

foreman start
