#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Setting up DB..."

brew services restart postgres

dropdb --if-exists willtherebespace
createdb willtherebespace

export DATABASE_URL=postgres://localhost/willtherebespace

source venv/bin/activate

alembic downgrade base
alembic upgrade head

deactivate

echo "==> App is now ready to go!"
