#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

script/bootstrap

progress "Setting up DB…"

dropdb --if-exists willtherebespace
createdb willtherebespace

export DATABASE_URL=postgresql://localhost/willtherebespace

source venv/bin/activate

alembic downgrade base
alembic upgrade head

deactivate

progress "App is now ready to go!"
