#!/bin/bash

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

script/bootstrap

progress "Updating DB…"

export DATABASE_URL=postgres://localhost/willtherebespace

source venv/bin/activate

alembic upgrade head

deactivate
